apiVersion: batch/v1
kind: Job
metadata:
  name: ui-test-job
spec:
  template:
    spec:
      containers:
        - name: test-runner
          image: ui-test-framework:latest
          imagePullPolicy: Never
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "=== Отладочная информация ==="
              echo "Рабочая директория: $(pwd)"
              echo "Список файлов:"
              ls -la

              echo "=== Запуск тестов ==="
              npm test -- --config=playwright.k8s.config.ts

              echo "=== Проверка папки с результатами тестов ==="
              ls -la allure-results || echo "Папка allure-results не найдена"

              echo "=== Генерация отчета Allure ==="
              if [ -d "allure-results" ] && [ "$(ls -A allure-results 2>/dev/null)" ]; then
                allure generate allure-results -o allure-report --clean
                echo "Отчет Allure сгенерирован:"
                ls -la allure-report || echo "Папка allure-report не найдена"
              else
                echo "Папка allure-results пуста или не существует"
              fi
          env:
            - name: DEBUG
              value: "pw:api"
            - name: TEST_ENV
              value: "local"
            - name: DISPLAY
              value: ":99"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: results-volume
              mountPath: /app/allure-results
            - name: reports-volume
              mountPath: /app/allure-report
      volumes:
        - name: results-volume
          emptyDir: {}
        - name: reports-volume
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 3
