apiVersion: v1
kind: Pod
metadata:
  name: ui-test-pod
spec:
  containers:
    - name: test-runner
      image: ${YOUR_DOCKER_REGISTRY}/ui-test-framework:latest
      args: ["test"]
      envFrom:
        - configMapRef:
            name: test-framework-config
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
      volumeMounts:
        - name: reports-volume
          mountPath: /app/allure-report
  volumes:
    - name: reports-volume
      persistentVolumeClaim:
        claimName: test-reports-pvc
  restartPolicy: Never
