name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run UI Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [local]
        browser: [chromium]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      # Запуск тестов - исправленная команда
      - name: Run tests
        continue-on-error: true
        run: |
          TEST_ENV=${{ matrix.environment }} npx playwright test --config=playwright.ci.config.ts
        env:
          CI: true
    
      # Генерация отчета Allure
      - name: Generate Allure Report
        if: always()
        run: allure generate allure-results -o allure-report --clean
        continue-on-error: true

      # Загрузка отчета Allure
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.environment }}-${{ matrix.browser }}
          path: allure-report/
          retention-days: 7
          if-no-files-found: warn